TRUE = "True"
FALSE = "False"
TRUE_FALSE = [TRUE, FALSE]

QUIZ_1_QUESTIONS = [
    dict(index=1, text="This study consists of 10 periods.", choices=TRUE_FALSE, table=None),
    dict(index=2, text="Each period consists of a hiring phase and a work phase.", choices=TRUE_FALSE, table=None),
    dict(index=3, text="In the hiring phase of each period, each employer <strong>must</strong> make a contract "
                       "offer to one worker.", choices=TRUE_FALSE, table=None,
         correct_text="Each employer does not have to make a contract offer to a worker."),
    dict(index=4, text="In the hiring phase of each period, workers review the offers they received and "
                       "<strong>must</strong> accept one offer.", choices=TRUE_FALSE, table=None),
    dict(index=5, text="If a worker rejects an offer received from an employer in the hiring phase of a period, "
                       "the worker <strong>will</strong> be able to receive another offer <strong>from the same "
                       "employer in that period</strong>.", choices=TRUE_FALSE, table=None),
    dict(index=6, text="Employer offers include a salary and whether training is provided during the period. "
                       "Regardless of the worker's effort decision during the subsequent work phase, the salary "
                       "and training specified in the accepted offer must be provided.", choices=TRUE_FALSE,
         table=None),
    dict(index=7, text="Employers and workers who do not contract in the hiring phase of a period receive only their "
                       "initial endowment for that period and do not complete the work phase. Employers do not receive "
                       "revenue from worker effort and workers do not receive a salary from an employer.",
         choices=TRUE_FALSE, table=None),
    dict(index=8, text="In the work phase of each period, every hired worker must decide how much effort to exert. "
                       "Higher levels of effort are <strong>more costly</strong> to the worker than lower levels of "
                       "effort.",
         choices=TRUE_FALSE, table=None),
    dict(index=9, text="For every worker skill level, the higher the level of effort a worker chooses, the higher an "
                       "employer's revenue is.", choices=TRUE_FALSE, table=None),
    dict(index=10, text="Worker's productivity is based on his/her skill level. The higher the worker's skill level, "
                        "the higher the worker's productivity is and, thus, the higher the revenue for the employer "
                        "is for a given effort level.", choices=TRUE_FALSE, table=None),
    dict(index=11, text="In the hiring phase in <strong>each</strong> of the 10 periods, every employer can again "
                        "select <strong>any</strong> potential worker to make a contract offer to and every worker "
                        "can freely accept one of the contract offers they receive.", choices=TRUE_FALSE, table=None),
]

QUIZ_2_QUESTIONS = [
        dict(index=1, text="If an employer provides training to a worker, he/she incurs a 50-point direct "
                           "training cost.", choices=TRUE_FALSE, table=None),
        dict(index=2, text="Providing training to workers is costly to employers not only because the employer "
                           "incurs a direct training cost of 50 points, but also because in a period with training "
                           "the employer will only receive half of the revenue that is generated by the combination "
                           "of the worker's skill level and the effort level chosen.", choices=TRUE_FALSE, table=None),
        dict(index=3, text="Receiving training is costly for workers.", choices=TRUE_FALSE, table=None),
        dict(index=4, text="If a worker receives training, his/her skill level will not increase until the following "
                           "period.", choices=TRUE_FALSE, table=None),
        dict(index=5, text="Increases in skill level are permanent and apply to all future periods.",
             choices=TRUE_FALSE, table=None),
        dict(index=6, text="When workers receive training in a period, they <strong>do not</strong> make effort "
                           "decisions in the work phase like they would if training was not provided.",
             choices=TRUE_FALSE, table=None),
]

QUIZ_3_QUESTIONS = [
        dict(index=1, text="What are a worker's earnings in a period in which he/she "
                           "<strong>does not</strong> accept any contract?", choices=[400, 550, 700], table=None),
        dict(index=2, text="What are an employer's earnings in a period in which he/she "
                           "<strong>does not</strong> hire any worker?", choices=[500, 650, 800], table=None),
        dict(index=3, text="Employers receive revenue based on the level of effort exerted by their workers "
                           "and the skill level of their workers. "
                           "Employer pay is decreased by the salary paid to the worker and, "
                           "when training is offered, training costs.", choices=TRUE_FALSE, table=None),
        dict(index=4, text="In case a worker accepts a contract offer of an employer that "
                           "<strong>does include</strong> training, the employer receives only "
                           "<strong>half of the revenue</strong> based on the hired worker's productivity (determined "
                           "by his/her skill level) and the effort level the worker chooses in this period.",
             choices=TRUE_FALSE, table=None),
        dict(index=5, text="Assume an employer offers a contract that includes a <strong>salary of 500</strong> points "
                           "and <strong>does not include training</strong>. "
                           "The worker who accepts the contract has a <strong>skill level of 5</strong> and chooses "
                           "an <strong>effort level of 5</strong>. Including the employer's initial endowment of "
                           "800 points, what are the employer's earnings in this period?",
             choices=[1510, 1210, 855, 710], table="_tables/global/revenue.html"),
        dict(index=6, text="Assume an employer offers a contract that <strong>includes a salary of 500 points</strong> "
                           "and training. The worker who accepts the contract has a <strong>skill level of 5</strong> "
                           "and chooses an <strong>effort level of 5</strong>. "
                           "Including the employer's initial endowment of 800 points, "
                           "what are the employer's earnings in this period?",
             choices=[1510, 1210, 855, 710], table="_tables/global/revenue.html"),
        dict(index=7, text="If a worker <strong>accepts</strong> a contract, the worker's earnings for this period "
                           "are comprised of the worker's initial endowment plus the salary paid to him/her by his/her "
                           "employer less the costs associated with the chosen level of effort.",
             choices=TRUE_FALSE, table=None),
        dict(index=8, text="Assume a worker accepts a contract that includes a <strong>salary of 500 points</strong> and "
                           "<strong>training</strong>. The worker has a skill level of 5 and chooses "
                           "an effort level of 5. Including the worker's initial endowment of 400 points, "
                           "what  would the <strong>worker's</strong> earnings be in this period?",
             choices=[900, 800, 400], table="_tables/intro_quiz/effort.html"),
]

QUIZ_1_ANSWERS = [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]
QUIZ_2_ANSWERS = [0, 0, 1, 0, 0, 1, 0, 0]
QUIZ_3_ANSWERS = [0, 2, 0, 0, 0, 2, 0, 1]

QUIZ_1_HINTS = [
    [
        "Your response is incorrect. This study consists of 10 periods. Please try again.",
        "Your response is correct. This study consists of 10 periods."
    ],
    [
        "Your response is incorrect. Each period consists of a hiring phase and a work phase. Please try again.",
        "Your response is correct. Each period consists of a hiring phase and a work phase."
    ],
    [
        "Your response is incorrect. In the hiring phase of each period, each employer "
        "<strong>does not have to</strong> make a contract offer to a worker. Please try again.",
        "Your response is correct. In the hiring phase of each period, each employer "
        "<strong>does not have to</strong> make a contract offer to a worker."
    ],
    [
        "Your response is incorrect. In the hiring phase of each period, workers review the offers they received and "
        "<strong>do not have to</strong> accept an offer. Please try again.",
        "Your response is correct.  In the hiring phase of each period, workers review the offers they received and "
        "<strong>do not have to</strong> accept an offer."
    ],
    [
        "Your response is incorrect. "
        "If a worker rejects an offer received from an employer in the hiring phase of a period, "
        "the worker will <strong>not</strong> be able to receive another offer from the same employer in that period. "
        "Please try again.",
        "Your response is correct. "
        "If a worker rejects an offer received from an employer in the hiring phase of a period, "
        "the worker will <strong>not</strong> be able to receive another offer from the same employer in that period."
    ],
    [
        "Your response is incorrect. Employer offers include a salary and whether training is provided during the "
        "period. Regardless of the worker's effort decision during the subsequent work phase, the salary and "
        "training specified in the accepted offer must be provided. Please try again.",
        "Your response is correct. Employer offers include a salary and whether training is provided during the "
        "period. Regardless of the worker's effort decision during the subsequent work phase, the salary and "
        "training specified in the accepted offer must be provided."
    ],
    [
        "Your response is incorrect. "
        "Employers and workers who do not contract in the hiring phase of a period receive only their "
        "initial endowment for that period and do not complete the work phase. Employers do not receive "
        "revenue from worker effort and workers do not receive a salary from an employer."
        " Please try again.",
        "Your response is correct. "
        "Employers and workers who do not contract in the hiring phase of a period receive only their "
        "initial endowment for that period and do not complete the work phase. Employers do not receive "
        "revenue from worker effort and workers do not receive a salary from an employer."
    ],
    [
        "Your response is incorrect. "
        "In the work phase of each period, every hired worker must decide how much effort to exert. Higher "
        "levels of effort are <strong>more costly</strong> to the worker than lower levels of effort."
        " Please try again.",
        "Your response is correct. "
        "In the work phase of each period, every hired worker must decide how much effort to exert. Higher "
        "levels of effort are <strong>more costly</strong> to the worker than lower levels of effort."
    ],
    [
        "Your response is incorrect. "
        "For every worker skill level, the higher the level of effort a worker chooses, the higher an "
        "employer's revenue is."
        " Please try again.",
        "Your response is correct. "
        "For every worker skill level, the higher the level of effort a worker chooses, the higher an "
        "employer's revenue is."
    ],
    [
        "Your response is incorrect. "
        "Worker's productivity is based on his/her skill level. The higher the worker's skill level, the "
        "higher the worker's productivity is and, thus, the higher the revenue for the employer is for "
        "a given effort level."
        " Please try again.",
        "Your response is correct. "
        "Worker's productivity is based on his/her skill level. The higher the worker's skill level, the "
        "higher the worker's productivity is and, thus, the higher the revenue for the employer is for "
        "a given effort level."
    ],
    [
        "Your response is incorrect. "
        "In the hiring phase in <strong>each</strong> of the 10 periods, every employer can again select "
        "<strong>any</strong> potential worker to make a contract offer to and every worker can freely "
        "accept one of the contract offers they receive."
        " Please try again.",
        "Your response is correct. "
        "In the hiring phase in <strong>each</strong> of the 10 periods, every employer can again select "
        "<strong>any</strong> potential worker to make a contract offer to and every worker can freely "
        "accept one of the contract offers they receive."
    ],
]

QUIZ_2_HINTS = [
    [
        "Your response is incorrect. If an employer provides training to a worker, he/she incurs a 50-point direct "
        "training cost. Please try again.",
        "Your response is correct. If an employer provides training to a worker, he/she incurs a 50-point direct "
        "training cost."
    ],
    [
        "Your response is incorrect. It is costly to employers not only because the employer incurs a direct "
        "training cost of 50 points, but also because in a period with training he/she will only receive "
        "half of the revenue generated by the worker. Please try again.",
        "Your response is correct. It is costly to employers not only because the employer incurs a direct "
        "training cost of 50 points, but also because in a period with training he/she will only receive "
        "half of the revenue generated by the worker."
    ],
    [
        "Your response is incorrect. Receiving training does not cost anything for workers. Please try again.",
        "Your response is correct. Receiving training does not cost anything for workers."
    ],
    [
        "Your response is incorrect. If a worker receives training, his/her skill level will not increase "
        "until the following period. Please try again.",
        "Your response is correct. If a worker receives training, his/her skill level will not increase "
        "until the following period."
    ],
    [
        "Your response is incorrect. Increases in skill level are permanent and apply to all future periods. "
        "Please try again.",
        "Your response is correct. Increases in skill level are permanent and apply to all future periods."
    ],
    [
        "Your response is incorrect. When workers receive training in a period, they <strong>do</strong> make effort "
        "decisions in the work phase like they would if training was not provided. Please try again.",
        "Your response is correct. When workers receive training in a period, they <strong>do</strong> make effort "
        "decisions in the work phase like they would if training was not provided."
    ]
]

QUIZ_3_HINTS = [
    [
        "Your response is incorrect. "
        "When a worker does not accept any contract, he/she only earns the 400 point endowment in that period. "
        "Please try again.",
        "Your response is correct. "
        "When a worker does not accept any contract, he/she only earns the 400 point endowment in that period."
    ],
    [
        "Your response is incorrect. When an employer does not hire any worker, he/she only earns the 800 "
        "point endowment in that period. Please try again.",
        "Your response is correct. When an employer does not hire any worker, he/she only earns the 800 "
        "point endowment in that period."
    ],
    [
        "Your response is incorrect. Employers receive revenue based on the level of effort exerted by their workers "
        "and the skill level of their worker. "
        "Employer pay is decreased by the salary paid to the worker and, when training is offered, training costs. "
        "Please try again.",
        "Your response is correct. Employers receive revenue based on the level of effort exerted by their workers "
        "and the skill level of their worker. "
        "Employer pay is decreased by the salary paid to the worker and, when training is offered, training costs."
    ],
    [
        "Your response is incorrect. In case a worker accepts a contract offer of an employer that "
        "<strong>does include</strong> training, the employer receives only <strong>half of the revenue</strong> based "
        "on the hired worker's productivity (determined by his/her skill level) "
        "and the effort level the worker chooses in this period. "
        "Please try again.",
        "Your response is correct. In case a worker accepts a contract offer of an employer that "
        "<strong>does include</strong> training, the employer receives only <strong>half of the revenue</strong> based "
        "on the hired worker's productivity (determined by his/her skill level) "
        "and the effort level the worker chooses in this period."
    ],
    [
        "Your response is incorrect. If an employer offers a contract with a salary of 500 points and no training "
        "and a worker with skill level = 5 accepts the offer and chooses an effort level of 5, "
        "the employer's earnings for the period would be calculated as follows:<br/><br/>"
        "Employer Endowment: +800<br/>"
        "Revenue from Worker Effort: +1210<br/>"
        "Salary Paid to Worker: -500<br/>"
        "Employer Earnings for this period: 1510<br/><br/>"
        "Please try again.",
        "Your response is correct. If an employer offers a contract with a salary of 500 points and no training "
        "and a worker with skill level = 5 accepts the offer and chooses an effort level of 5, "
        "the employer's earnings for the period would be calculated as follows:<br/>"
        "Employer Endowment: +800<br/>"
        "Revenue from Worker Effort: +1210<br/>"
        "Salary Paid to Worker: -500<br/>"
        "Employer Earnings for this period: 1510"
    ],
    [
        "Your response is incorrect."
        "If an employer offers a contract with a salary of 500 points and provides training "
        "and a worker with skill level = 5 accepts the offer and chooses an effort level of 5, "
        "the employer's earnings for the period would be calculated as follows:<br/><br/>"
        "Employer Endowment: +800<br/>"
        "Revenue from Worker Effort: +605 (½ of 1210)<br/>"
        "Direct Training Costs: -50<br/>"
        "Salary Paid to Worker: -500<br/>"
        "Employer Earnings for this period: 855<br/><br/>"
        "Please try again.",
        "Your response is correct."
        "If an employer offers a contract with a salary of 500 points and provides training "
        "and a worker with skill level = 5 accepts the offer and chooses an effort level of 5, "
        "the employer's earnings for the period would be calculated as follows:<br/><br/>"
        "Employer Endowment: +800<br/>"
        "Revenue from Worker Effort: +605 (½ of 1210)<br/>"
        "Direct Training Costs: -50<br/>"
        "Salary Paid to Worker: -500<br/>"
        "Employer Earnings for this period: 855"
    ],
    [
        "Your response is incorrect.If a worker <strong>accepts</strong> a contract, the worker's earnings "
        "for this period are comprised of the worker's initial endowment plus the salary paid to him/her "
        "by his/her employer less the costs associated with the chosen level of effort."
        "Please try again.",
        "Your response is correct.If a worker <strong>accepts</strong> a contract, the worker's earnings "
        "for this period are comprised of the worker's initial endowment plus the salary paid to him/her "
        "by his/her employer less the costs associated with the chosen level of effort."
    ],
    [
        "Your response is incorrect."
        "If a worker accepts a contract with a salary of 500 points and chooses an effort level of 5, "
        "the worker's earnings for the period would be calculated as follows:<br/><br/>"
        "Worker Endowment: +400<br/>"
        "Salary: +500<br/>"
        "Cost of Effort: -100<br/>"
        "Worker Earnings for this period: 800<br/><br/>"
        "Please try again.",
        "Your response is correct."
        "If a worker accepts a contract with a salary of 500 points and chooses an effort level of 5, "
        "the worker's earnings for the period would be calculated as follows:<br/><br/>"
        "Worker Endowment: +400<br/>"
        "Salary: +500<br/>"
        "Cost of Effort: -100<br/>"
        "Worker Earnings for this period: 800"
    ],
]

def get_questions(quiz_number: int, player: "Player") -> list[dict[str, int | str | list[str]]]:
    match quiz_number:
        case 0:
            return QUIZ_1_QUESTIONS
        case 1:
            q_2_7 = dict(index=7, text=player.q_2_7_text, choices=TRUE_FALSE, table=None)
            q_2_8 = dict(index=8, text=f"Your skill level in the first period is <strong>{player.skill}</strong>.",
                         choices=TRUE_FALSE, table=None)
            return QUIZ_2_QUESTIONS + ([q_2_7, q_2_8] if player.role == "Employee" else [q_2_7])
        case 2:
            return QUIZ_3_QUESTIONS
        case _:
            raise ValueError(f"Not supported quiz number {quiz_number}.")


def get_answers(quiz_number: int) -> list[int]:
    return [QUIZ_1_ANSWERS, QUIZ_2_ANSWERS, QUIZ_3_ANSWERS][quiz_number]


def get_hints(quiz_number: int, player: "Player") -> list[list[str]]:
    match quiz_number:
        case 0:
            return QUIZ_1_HINTS
        case 1:
            q_2_7 = [
                f"Your response is incorrect. In the first period, all workers start with a skill level of "
                f"{player.q_2_7_text}. Please try again.",
                f"Your response is correct. In the first period, all workers start with a skill level of "
                f"{player.q_2_7_text}."
            ]
            q_2_8 = [
                f"Your response is incorrect. Your skill level in the first period is <strong>{player.skill}</strong>. "
                f"Please try again.",
                f"Your response is correct. Your skill level in the first period is <strong>{player.skill}</strong>."
            ]
            return QUIZ_2_HINTS + [q_2_7, q_2_8]
        case 2:
            return QUIZ_3_HINTS
        case _:
            raise ValueError(f"Not supported quiz number {quiz_number}.")